### ISSUE TITLE
Add to frontend an item presenting the buy/sell suggestions and trends

### ISSUE THREAD

**Issue by grzjan5219** [grzjan5219/InvestMe#1]
The goal of this feature is to analyse the latest data and present trends on the webapp. AS a result of the analysis we would like to get the suggestions about selling/buying crypto.

**Comment by grzjan5219** [comment]
The goal of this feature is to analyse the latest data and present trends on the webapp. AS a result of the analysis we would like to get the suggestions about selling/buying crypto.

**Comment by Schoji** [comment]
Already added, thanks. 

![image](https://user-images.githubusercontent.com/96655599/151708207-0519c58c-6c43-4c50-a8b3-1b7640c0d6a3.png)
